### ISSUE TITLE
[FR] Create opacity styles without color or other attributes.

### ISSUE THREAD

**Issue by mikebronner** [ingrammicro/puzzle-tokens#10]
It is beneficial to create styles that only contain opacity settings without any other attributes. This would allow us to apply them to groups and other containers as a whole.

I attempted this, but the plugin doesn't seem to create the styles correctly. I tried both decimal and percentage values.
```less
.Opacities .0 {
  opacity: 0;
}
.Opacities .25 {
  opacity: 0.25;
}
.Opacities .50 {
  opacity: 0.5;
}
.Opacities .75 {
  opacity: 0.75;
}
.Opacities .100 {
  opacity: 1;
}
```
