### ISSUE TITLE
[FR] Add text transformation options.

### ISSUE THREAD

**Issue by mikebronner** [ingrammicro/puzzle-tokens#11]
- uppercase
- lowercase
- capitalize (this doesn't appear to be supported in Sketch?)
- none

**Comment by MaxBazarov** [comment]
Please check Plugin description.
It contains the followiung:
text-transform:        uppercase; // "uppercase", "lowercase", and "none"

capitalize is not supported by Sketch

**Comment by mikebronner** [comment]
Hmmm, I added transforms to my less scripts, but they don't seem to work when importing the styles. I'll try again when I get to the office, thanks.

**Comment by mikebronner** [comment]
Here are the results I am seeing:
```less
@import "./_tailwind-variables.less";

@rootFontSize: 16px;

@colors: {
    Gray: gray;
    Red: red;
    Orange: orange;
    Yellow: yellow;
    Green: green;
    Teal: teal;
    Blue: blue;
    Indigo: indigo;
    Purple: purple;
    Pink: pink;
};

@variants:
    100,
    200,
    300,
    400,
    500,
    600,
    700,
    800,
    900
;

@sizes:
    xs,
    sm,
    base,
    lg,
    xl,
    2xl,
    3xl,
    4xl,
    5xl,
    6xl
;

@weights-mono:
    400,
    700,
;

@weights-sans:
    100,
    200,
    400,
    500,
    600,
    700,
    800,
    900,
;

@weights-serif:
    400,
    700,
;

@lineheights: {
    none: 1;
    tight: 1.25;
    snug: 1.375;
    normal: 1.5;
    relaxed: 1.625;
    loose: 2;
};

@letterSpacings: {
    tighter: -0.05em;
    tight: -0.025em;
    normal: 0;
    wide: 0.025em;
    wider: 0.05em;
    widest: 0.1em;
};

@styles:
    italic,
    normal
;

@decorations:
    underline,
    line-through,
    none,
;

@transformations:
    uppercase,
    lowercase,
    capitalize,
    none,
;

@horizontalAligns:
    left,
    center,
    right,
    justify,
;

@verticalAligns:
    top,
    middle,
    bottom,
;

@families: {
    sans: "SF Pro Display";
    serif: Georgia;
    mono: Menlo;
};

each(@families, .(@fontName, @family) {
    each(@sizes, .(@size) {
        @fontSize: "fontSize-@{size}";
        @fontSizePx: @rootFontSize * @@fontSize;
        @weights: "weights-@{family}";
        each(@@weights, .(@weight) {
            each(@styles, .(@style) {
                // each(@decorations, .(@decoration) {
                    each(@transformations, .(@transformation) {
                        // each(@verticalAligns, .(@verticalAlign) {
                            // each(@horizontalAligns, .(@horizontalAlign) {
                                each(@lineheights, .(@lineheight, @lineheightName) {
                                    // each(@letterSpacings, .(@letterSpacing, @letterSpacingName) {
                                        .@{family} .@{fontSizePx}__-__@{size} .Lineheight__-__@{lineheightName} .@{transformation} .@{style} .@{weight} {
                                            font-family: @fontName;
                                            font-size: @fontSizePx;
                                            font-weight: @weight;
                                            font-style: @style;
                                            color: black;
                                            line-height: @lineheight;
                                            // letter-spacing: @letterSpacing;
                                            // text-decoration: @decoration;
                                            text-transform: @transformation;
                                            // vertical-align: @verticalAlign;
                                            // text-align: @horizontalAlign;
                                        }
                                    // });
                            //     });
                            // });
                        });
                    });
                // });
            });
        });
    });
});
```

<img width="1712" alt="Screen Shot 2019-11-19 at 6 13 04 AM" src="https://user-images.githubusercontent.com/1791050/69153819-c2081000-0a93-11ea-9a95-bad576fb8318.png">
